Refactored build commands

diff --git a/sdlc/deploy b/sdlc/deploy
--- a/sdlc/deploy
+++ b/sdlc/deploy
@@ -34,10 +34,20 @@ if [ $? -ne 0 ]; then
     handle_error "Django Environment Update failed. Exiting..."
 fi
 
-# Build Docker image
+# Start Docker Build process
+echo -e "${YELLOW}Starting Docker Build Prcess...${NC}"
 bash ~/bin/sdlc/build
 if [ $? -ne 0 ]; then
     handle_error "Build script failed. Exiting..."
+fi
+
+# Build Web Image
+echo -e "${YELLOW}Building Web image...${NC}"
+docker compose build web
+if [ $? -ne 0 ]; then
+    echo -e "${RED}Docker web image build failed. Exiting...${NC}"
+    echo -e " "
+    exit 1
 fi
 
 # Push Docker images to Docker Hub
diff --git a/sdlc/test_code b/sdlc/test_code
--- a/sdlc/test_code
+++ b/sdlc/test_code
@@ -3,8 +3,20 @@
 # Set Colors and handle errors
 source ~/bin/colors
 
-# Build Docker image
-~/bin/sdlc/build
+# Start Docker Build process
+bash ~/bin/sdlc/build
+if [ $? -ne 0 ]; then
+    handle_error "Build script failed. Exiting..."
+fi
+
+# Build CI/CD Image
+echo -e "${YELLOW}Building CI/CD image...${NC}"
+docker compose build check_code
+if [ $? -ne 0 ]; then
+    echo -e "${RED}Docker CI/CD image build failed. Exiting...${NC}"
+    echo -e " "
+    exit 1
+fi
 
 # Check if check_code executable exists and is executable
 if [ ! -x "${PWD}/sdlc/check_code" ]; then
diff --git a/sdlc/test_run b/sdlc/test_run
--- a/sdlc/test_run
+++ b/sdlc/test_run
@@ -34,15 +34,25 @@ if [ $? -ne 0 ]; then
     handle_error "Django Environment Update failed. Exiting..."
 fi
 
-# Build Docker image
+# Start Docker Build process
+echo -e "${YELLOW}Starting Docker Build Prcess...${NC}"
 bash ~/bin/sdlc/build
 if [ $? -ne 0 ]; then
     handle_error "Build script failed. Exiting..."
 fi
 
+# Build Local Web Image
+echo -e "${YELLOW}Building Local Web image...${NC}"
+docker compose build local_web
+if [ $? -ne 0 ]; then
+    echo -e "${RED}Docker local_web image build failed. Exiting...${NC}"
+    echo -e " "
+    exit 1
+fi
+
 # Run Docker image Locally
 echo -e "${YELLOW}Running Docker image Locally...${NC}"
-docker compose up local_web --remove-orphans 
+docker compose run local_web
 if [ $? -ne 0 ]; then
     echo -e "${RED}Creating Docker container failed. Exiting...${NC}"
     echo -e " "
