Added image tagging

diff --git a/sdlc/deploy b/sdlc/deploy
--- a/sdlc/deploy
+++ b/sdlc/deploy
@@ -38,6 +38,10 @@ if [ $? -ne 0 ]; then
     handle_error "Build script failed. Exiting..."
 fi
 
+# Define repository and tag variables
+DOCKER_REPO="${DOCKER_USERNAME}/web"
+IMAGE_TAG="latest"
+
 # Build Web Image
 echo -e "${YELLOW}Building Web image...${NC}"
 docker compose build web
@@ -59,12 +63,21 @@ else
     echo -e " "
 fi
 
+# Tag the image
+echo -e "${YELLOW}Tagging Web image...${NC}"
+docker tag web:latest $DOCKER_REPO:$IMAGE_TAG
+if [ $? -ne 0 ]; then
+    echo -e "${RED}Failed to tag the Web image. Exiting...${NC}"
+    echo -e " "
+    exit 1
+else
+    echo -e "${GREEN}Web image tagged as $DOCKER_REPO:$IMAGE_TAG.${NC}"
+    echo -e " "
+fi
+
 # Push Docker images to Docker Hub
 echo -e "${YELLOW}Pushing Docker images to Docker Hub...${NC}"
-
-# Push Web Image
-echo -e "${YELLOW}Pushing Database image...${NC}"
-push_output=$(docker compose push web 2>&1)
+push_output=$(docker push $DOCKER_REPO:$IMAGE_TAG 2>&1)
 
 # Check if 'skipped' appears in the output
 if echo "$push_output" | grep -q "skipped"; then
@@ -86,6 +99,5 @@ else
     echo -e " "
 fi
 
-echo -e "${GREEN}Docker images successfully pushed to Docker Hub!${NC}"
 echo -e "${GREEN}Deployment script completed successfully!${NC}"
 echo -e " "
