Fixed build flow

diff --git a/sdlc/test_code b/sdlc/test_code
--- a/sdlc/test_code
+++ b/sdlc/test_code
@@ -4,9 +4,42 @@
 source ~/bin/colors
 
 # Start Docker Build process
+echo -e "${YELLOW}Starting Docker Build Prcess...${NC}"
 bash ~/bin/sdlc/build
 if [ $? -ne 0 ]; then
     handle_error "Build script failed. Exiting..."
+fi
+
+# Stop any running containers using port 8000 (optional)
+echo -e " "
+echo -e "${YELLOW}Stopping containers using Port 8000...${NC}"
+echo -e " "
+
+# Capture the output of the docker stop command
+stopped_containers=$(docker ps -q --filter "ancestor=web")
+
+if [ -n "$stopped_containers" ]; then
+    docker stop $stopped_containers
+    if [ $? -ne 0 ]; then
+        echo -e "${RED}Failed to stop running containers using port 8000. Exiting...${NC}"
+        echo -e " "
+        exit 1
+    else
+        echo -e "${GREEN}Successfully stopped containers using port 8000.${NC}"
+        echo -e " "
+    fi
+else
+    echo -e "${GREEN}No containers found using port 8000. Skipping stop step.${NC}"
+    echo -e " "
+fi
+
+# Build Local Web Image
+echo -e "${YELLOW}Building Local Web image...${NC}"
+docker compose build local_web
+if [ $? -ne 0 ]; then
+    echo -e "${RED}Docker local_web image build failed. Exiting...${NC}"
+    echo -e " "
+    exit 1
 fi
 
 # Build CI/CD Image
