Added functionality to also prune images from docker.

diff --git a/sdlc/test_code b/sdlc/test_code
--- a/sdlc/test_code
+++ b/sdlc/test_code
@@ -6,13 +6,24 @@ source ~/bin/colors
 # Define cleanup function
 cleanup() {
     echo -e " "
-    echo -e "${YELLOW}Cleaning up and stopping Docker containers...${NC}"
+    echo -e "${YELLOW}Stopping & Clearing Docker containers...${NC}"
     docker compose down
     if [ $? -ne 0 ]; then
         echo -e "${RED}Failed to stop Docker containers. Please check manually.${NC}"
         echo -e " "
     else
         echo -e "${GREEN}Docker containers stopped successfully.${NC}"
+        echo -e " "
+    fi
+
+    echo -e " "
+    echo -e "${YELLOW}Stopping & Pruning Docker images...${NC}"
+    docker image prune -a
+    if [ $? -ne 0 ]; then
+        echo -e "${RED}Failed to prune Docker images. Please check manually.${NC}"
+        echo -e " "
+    else
+        echo -e "${GREEN}Docker images pruned successfully.${NC}"
         echo -e " "
     fi
 }
